### PR TITLE
Import records from CRM 

### PR DESCRIPTION
**Pull request by ProgrammerZ**
Added Import Module to import records (contact|account|vendor) from CRM
$zohoBooks->import->contact('zoho_crm_contact_id');

### CODE REVIEW

**Comment by Skullbock** [comment]
Hi! Thanks for the very interesting PR!

Can i ask you to review my suggestions? I like the idea, but i think we can do a better Developer Experience around this:

1. I don't think we need a new Model for this, just a new module.
2. I my mind the ```importFromCrm``` should be in the ```Import``` Module, not in the base one.
3. Instead of returning the ```Import``` model from each import call, why don't we return the corresponding Model? For example, on ```$zohoBooks->import->contact($id)``` we should return a ```Contact``` model instance, and so on.

What do you think?
Thanks again!

**Comment by ProgrammerZ** [comment]
1. I wanted to be consistent, since I saw some other models are also empty. Although I accustomed to work with collections, array it absolutely fine on return.
2. Absolutely agree, I was already tired, there is no need `importFromCrm` to be in the `Module` class.
3. Not sure about it, since the data that is returned is not consistent. For example `Import` return `data->customer_id`  and `Contact` returns `data->contact_id`. Also I would expect to get full contact data in `Contact` model, but `Import` response have only few data points:
```
#data: array:3 [▼
    "code" => 0
    "message" => "success"
    "data" => array:1 [▼
      "customer_id" => "1111111111111111111"
    ]
  ]
```
I'm still considering myself a beginner, so you are the boss here. ;)

**Comment by Skullbock** [comment]
I'll comment on the code so it's more clear ;)

**Comment by ProgrammerZ** [comment]
Great! It's my first pull request, I'm not sure how to move `importFromCrm`. Do I create another pull request or you can change it?

**Comment by Skullbock** [comment]
Hey, no just push to your repo where you made this changes, this PR will get updated automatically

**Comment by ProgrammerZ** [comment]
Pushed it. Sorry for delay.

**Comment by Skullbock** [comment]
Hey, i pushed some more changed to deal with the refactor i mentioned.

https://github.com/Weble/ZohoBooksApi/pull/46/commits/9b435da321602fb9ecb5c224e33df41636305844

Can you test the results and tell me if it works for you so i can merge?

Thanks

**Comment by Skullbock** [comment]
@ProgrammerZ can you please test this updated PR to check if it still works as you intended?
Thanks

**Comment by ProgrammerZ** [comment]
@Skullbock Sorry, had health issues. I have tested the code and and had some errors: 
Commented inside the pull  [9b435da](https://github.com/Weble/ZohoBooksApi/commit/9b435da321602fb9ecb5c224e33df41636305844)

**Comment by Skullbock** [comment]
Hey @ProgrammerZ sorry to hear that, i hope all is well now.

I pushed a couple of fixes, can you test again?

P.s.: strangely zoho books api is not up to date: https://www.zoho.com/books/api/v3/#ZOHO_CRM_Integration_Import_a_customer_using_the_CRM_account_ID (customer_id vs contact_id)

**Comment by ProgrammerZ** [comment]
I'm better now, thanks @Skullbock. 

It works. 

But I would add try block around `$this->client->post` in case there is no record found in Books while importing: 
`$zohoBooks->import->contact('{non-existent-id}');`

It returns `\GuzzleHttp\Exception\ClientException` with message 
`Client error: POST https://books.zoho.com/api/v3/crm/contact/44444444444444444/import?organization_id=777777777 resulted in a 404 Not Found response: {"code":1002,"message":"Resource does not exist."}` 

    try {
         $data = $this->client->post(
             'crm/' . $urlPath . '/'. $crm_id . '/import', ['blank'=>'']
         );
    } catch (\GuzzleHttp\Exception\ClientException  $e) {
        throw new ErrorResponseException('Response from Zoho is not success. Message: ' . $e->getMessage(), $e- 
    >getCode() ?? 500);
    }

**Comment by Skullbock** [comment]
Thanks for the notice, added the check.
Closing and merging, thanks again for the help!

**Pull request merged**
