### PR TITLE
Fixed bug: change deprecated package doctrine/inflector with mmucklo/inflect

### PR DESCRIPTION
**Pull request by MajidPro320**
Hello
Thanks a lot for this package.
and thank you for your review.

### CODE REVIEW

**Comment by Skullbock** [comment]
Hi! Thank you for you PR! Can you point me to a resource where it states that doctrine/inflector is deprecated? 
I couldn't find anything on their repo

Thanks!

**Comment by MajidPro320** [comment]
You're welcome
Yes of course

your package requires the "doctrine/inflector": "^1.4" in composer.json and after run code I get an exception
****
An exception has occurred.
Deprecated: The "Doctrine\Common\Inflector\Inflector::pluralize" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.
****

and also I can not update the package "doctrine/inflector": "^1.4" to the last version.

**Comment by Skullbock** [comment]
Hey, thanks, but i preferred to keep doctrine as a dependency.
I've updated the code and released 4.2.0 to avoid getting the deprecated message

https://github.com/Weble/ZohoBooksApi/commit/2d223c6c47f3bd4561ad1e590a30ac62803e7c97

Cheers!

**Comment by MajidPro320** [comment]
Thanks

**Pull request closed without merging**
