### PR TITLE
fix: add getApiKeyName() to RecurringInvoices

### PR DESCRIPTION
**Pull request by mhallhol**
Update getApiKeyName() under RecurringInvoices module, to allow getList() method to function correctly

### CODE REVIEW

**Comment by Skullbock** [comment]
Good catch!

**Comment by Skullbock** [comment]
Released 5.2.4

**Comment by mhallhol** [comment]
Thank you! This should also mean #78 can be closed

**Comment by Skullbock** [comment]
Thanks for the notice :)

**Pull request merged**
