### PR TITLE
Support Guzzle 6 or 7

### PR DESCRIPTION
**Pull request by tm1000**
There's no changes I can think of in Guzzle 7 that would effect this package

### CODE REVIEW

**Comment by Skullbock** [comment]
Thanks @tm1000 !

**Comment by tm1000** [comment]
@Skullbock would you also be able to do a release?

**Comment by Skullbock** [comment]
I want to wait and update the collection stuff too. Can you wait a couple of days?

**Comment by tm1000** [comment]
@Skullbock not a problem. I work with @xrobau in the same company actually, some of our stuff is using Laravel 8 which requires Guzzle 7, Rob pinned Laravel 8 to guzzle 6 for the time being. Seems to work for now.

**Comment by Skullbock** [comment]
Oh great to know. We work a lot with laravel too, but no project of ours has laravel and this api package yet

**Comment by xrobau** [comment]
> We work a lot with laravel too, but no project of ours has laravel and this api package yet

In case you don't know, @tm1000 and I were the FreePBX guys for a long time. And we have sworn mighty oaths never to do something as dumb as write our own autoloader, or implement something that someone has already spent huge amounts of time one again.  Hence Laravel (and us submitting a bunch of PRs here, too!)

**Comment by Skullbock** [comment]
Oh i remember FreePBX with fondness 👍 

Anyway, pushed 4.4.0 with this change and collections ;)

**Pull request merged**
