### PR TITLE
Adds ability to get list with page_context

### PR DESCRIPTION
**Pull request by tm1000**
As an alternative to `getList` this adds a `getListWithPageContext`. Where as the `page_context` is returned as a key inside of a collection of 'items'. The reasoning for this is because I discovered that sending response_option=1 will actually make zoho reply with the total number of records which is useful for pagination. This also works without `response_option` set (which means that total is just null but you get other options like getHasMorePage)

This also doesn't affect any current operations as it's a whole new method.

### CODE REVIEW

**Comment by Skullbock** [comment]
What to you think of implementing this the same way of zoho crm library?

https://github.com/Weble/ZohoCrmApi/blob/master/src/Modules/Module.php

**Comment by tm1000** [comment]
oh! i should have looked! Let me do this with that as its much better. The only difference is that I'd like to add total and totalPages because those are returned if response_option=1

**Comment by tm1000** [comment]
Ok all done and tested in my work. It works great! Thanks for the reference @Skullbock

**Comment by Skullbock** [comment]
Great job! this is super cool because it's not a BC change since `RecordCollection` extends `Collection` and only adds the relevant methods. 

Gonna tag a new minor release with this

**Comment by tm1000** [comment]
@Skullbock poke, tag that minor release! :-)

**Comment by Skullbock** [comment]
It's tagged...? Does packagist have issues again?

**Comment by tm1000** [comment]
@Skullbock Looking at tags and releases on github the last issued one was 25 days ago (https://github.com/Weble/ZohoBooksApi/releases)

**Comment by Skullbock** [comment]
Because i'm an idiot. I wrote 4.2.0 instead of 5.2.0, and of course it didn't work :(
Pushed again!

**Pull request merged**
