### PR TITLE
get exchange rate of a currency not working

### PR DESCRIPTION
**Pull request by romerpt**
Getting currency is not working.
$ExchangeRates = $zohoBooks->settings->currencies->getExchangeRates('28245000000000059');

If I use postman it works.
Postman_7cAjg2e4ti

Here is the example of how I'm calling it, I receive a lot of data but unable to get what I want.
tZAcWacstj

### CODE REVIEW

**Comment by Skullbock** [comment]
The PR seems empty, are you sure you committed the changes you made to make this work?

**Comment by romerpt** [comment]
Hi,

Sorry I'm new to use github and I thought you wanted me to only report the issue from here.

I know what the issue is:

when doing the get request the URL is passing "settings/currencies/28245000000000059" when it should be "settings/currencies/28245000000000059/exchangerates".

If you tell me where we can adjust change this I can change the code.

**Comment by Skullbock** [comment]
Try changing this:
https://github.com/Weble/ZohoBooksApi/blob/develop/src/Modules/Settings/Currencies/ExchangeRates.php#L29

into `exchangerates`

**Comment by romerpt** [comment]
Hi there,

Still not working getting the same output, that is the currency.

object(Webleit\ZohoBooksApi\Modules\Settings\Currencies\ExchangeRates)#855 (3) {
  ["parent":protected]=>
  object(Webleit\ZohoBooksApi\Models\Settings\Currency)#2718 (3) {
    ["data":protected]=>
    array(8) {
      ["currency_id"]=>
      string(17) "28245000000000059"
      ["currency_code"]=>
      string(3) "USD"
      ["currency_name"]=>
      string(20) "United States Dollar"
      ["currency_name_formatted"]=>
      string(25) "USD- United States Dollar"
      ["currency_symbol"]=>
      string(1) "$"
      ["price_precision"]=>
      int(2)
      ["currency_format"]=>
      string(12) "1,234,567.89"
      ["is_base_currency"]=>
      bool(false)
    }
    ["module":protected]=>
    object(Webleit\ZohoBooksApi\Modules\Settings\Currencies)#867 (2) {
      ["client":protected]=>
      object(Webleit\ZohoBooksApi\Client)#839 (7) {
        ["regionDomain":protected]=>
        array(5) {
          ["US"]=>
          string(30) "https://books.zoho.com/api/v3/"
          ["AU"]=>
          string(33) "https://books.zoho.com.au/api/v3/"
          ["EU"]=>
          string(29) "https://books.zoho.eu/api/v3/"
          ["IN"]=>
          string(29) "https://books.zoho.in/api/v3/"
          ["CN"]=>
          string(33) "https://books.zoho.com.cn/api/v3/"
        }
....

**Comment by Skullbock** [comment]
I'll try to debug this later this week but it's not a feature we're currently using so i'll not be able to give it a high priority.
if you can investigate this further and PR a fix, i'll merge it gladly

**Comment by romerpt** [comment]
I totally understand, I will try to see what I can do.

**Pull request merged**
