### PR TITLE
Fixing the casing of the classes

### PR DESCRIPTION
**Pull request by jpvaillancourt**
The last fix didn't work for me. Here's a suggestion to fix the problem. It was done yesterday before the last commit but just did my fork this morning so I had to revert your last commit.

### CODE REVIEW

**Comment by jcarignan** [comment]
Works for me!

**Comment by Skullbock** [comment]
Hi @jcarignan @jpvaillancourt And thanks for both the PR and the tests.
I took you suggestion and reworked your PR into a new release, using the class name instead of trying to generate it from the lower case version.

I prefer it this way, since it's more explicit than both my previous version and your suggested implementation.

What do you think?

**Comment by jpvaillancourt** [comment]
@Skullbock Yeah I think it would preferable since there's no way to find the classes programmatically when you start from a lowercased version of the name.

I'm going to try it again later. Is it already released?

**Comment by Skullbock** [comment]
Yes, i already pushed the new minor version 2.1.2

https://packagist.org/packages/webleit/zohobooksapi

**Comment by Skullbock** [comment]
Hi @jpvaillancourt can you confirm that’s working for you now? Sorry to bother you 😊

**Comment by Skullbock** [comment]
Closing for now, if this issue arises again, feel free to open a new issue / PR

**Pull request closed without merging**
